name: base

on:
  pull_request:
    branches:
      - 'master'
    paths:
      - '.github/workflows/base.yaml'
      - 'docker/base/**'
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/base.yaml'
      - 'docker/base/**'
    tags:
      - 'base-*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        if: startsWith(github.ref, 'refs/tags/base-')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Login to GHCR
        if: startsWith(github.ref, 'refs/tags/base-')
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/base
          file: ./docker/base/Dockerfile
          push: ${{ startsWith(github.ref, 'refs/tags/base-') }}
          tags: |
            crazymax/xgo:base
            ghcr.io/crazy-max/xgo:base
      -
        name: Docker Push
        if: startsWith(github.ref, 'refs/tags/base-')
        run: |
          docker push crazymax/xgo
          docker push ghcr.io/crazy-max/xgo
