name: build

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'

env:
  DOCKERHUB_SLUG: crazymax/xgo
  GHCR_SLUG: ghcr.io/crazy-max/xgo

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.xgo-cache
          key: ${{ runner.os }}-xgo-base-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-xgo-base-
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/bake-action@v1
        with:
          targets: base
          set: |
            *.tags=xgo:base
            *.output=type=docker,dest=/tmp/base.tar
            *.cache-from=type=local,src=/tmp/.xgo-cache
            *.cache-to=type=local,dest=/tmp/.xgo-cache-new
      -
        name: Upload base image
        uses: actions/upload-artifact@v2
        with:
          name: base
          path: /tmp/base.tar
      -
        # FIXME: https://github.com/docker/build-push-action/issues/252
        name: Move cache
        run: |
          rm -rf /tmp/.xgo-cache
          mv /tmp/.xgo-cache-new /tmp/.xgo-cache

  test:
    runs-on: ubuntu-latest
    needs: [ init ]
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.15
          - 1.16
        case:
          - c
          - cpp
          - gorm
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
      -
        name: Download base image
        uses: actions/download-artifact@v2
        with:
          name: base
          path: /tmp
      -
        name: Load Docker image
        run: |
          docker load --input /tmp/base.tar
          docker image inspect xgo:base
      -
        name: Bootstrap ${{ matrix.go_version }}
        uses: docker/bake-action@v1
        with:
          targets: go-${{ matrix.go_version }}
          set: |
            *.tags=xgo:${{ matrix.go_version }}
            *.output=type=docker
        env:
          BASE_IMAGE: xgo:base
      -
        name: Test ${{ matrix.case }} for go-${{ matrix.go_version }}
        uses: docker/bake-action@v1
        with:
          targets: test-${{ matrix.case }}
        env:
          BASE_IMAGE: xgo:${{ matrix.go_version }}

  base:
    runs-on: ubuntu-latest
    needs: [ init ]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.xgo-cache
          key: ${{ runner.os }}-xgo-base-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-xgo-base-
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            ${{ env.DOCKERHUB_SLUG }}
            ${{ env.GHCR_SLUG }}
          tag-custom: |
            base
          tag-custom-only: true
          label-custom: |
            org.opencontainers.image.title=xgo
            org.opencontainers.image.description=Go CGO cross compiler
            org.opencontainers.image.vendor=CrazyMax
      -
        name: Login to DockerHub
        if: startsWith(github.ref, 'refs/tags/base-')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Login to GHCR
        if: startsWith(github.ref, 'refs/tags/base-')
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build
        uses: docker/bake-action@v1
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.docker_meta.outputs.bake-file }}
          targets: base
          set: |
            *.cache-from=type=local,src=/tmp/.xgo-cache
            *.cache-to=type=local,dest=/tmp/.xgo-cache-new
          push: ${{ startsWith(github.ref, 'refs/tags/base-') }}
      -
        # FIXME: https://github.com/docker/build-push-action/issues/252
        name: Move cache
        run: |
          rm -rf /tmp/.xgo-cache
          mv /tmp/.xgo-cache-new /tmp/.xgo-cache

  go:
    runs-on: ubuntu-latest
    needs: [ init ]
    env:
      LATEST_116: 1.16.1
      LATEST_115: 1.15.9
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.15.0
          - 1.15.1
          - 1.15.2
          - 1.15.3
          - 1.15.4
          - 1.15.5
          - 1.15.6
          - 1.15.7
          - 1.15.8
          - 1.15.9
          - 1.16.0
          - 1.16.1
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Download base image
        uses: actions/download-artifact@v2
        with:
          name: base
          path: /tmp
      -
        name: Load Docker image
        run: |
          docker load --input /tmp/base.tar
          docker image inspect xgo:base
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
      -
        name: Prepare
        run: |
          TAGS="${{ matrix.go_version }}"
          if [ "${{ env.LATEST_116 }}" = "${{ matrix.go_version }}" ]; then
            TAGS="${TAGS},1.16.x,latest"
          elif [ "${{ env.LATEST_115 }}" = "${{ matrix.go_version }}" ]; then
            TAGS="${TAGS},1.15.x"
          fi
          echo "TAGS=${TAGS}" >> $GITHUB_ENV
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            ${{ env.DOCKERHUB_SLUG }}
            ${{ env.GHCR_SLUG }}
          tag-custom: |
            ${{ env.TAGS }}
          tag-custom-only: true
          label-custom: |
            org.opencontainers.image.title=xgo
            org.opencontainers.image.description=Go CGO cross compiler
            org.opencontainers.image.version=go-${{ matrix.go_version }}
            org.opencontainers.image.vendor=CrazyMax
      -
        name: Login to DockerHub
        if: startsWith(github.ref, 'refs/tags/go-')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Login to GHCR
        if: startsWith(github.ref, 'refs/tags/go-')
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build
        uses: docker/bake-action@v1
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.docker_meta.outputs.bake-file }}
          targets: go-${{ matrix.go_version }}
          push: ${{ startsWith(github.ref, 'refs/tags/go-') }}
        env:
          BASE_IMAGE: xgo:base

  xgo:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build artifacts
        uses: docker/bake-action@v1
        with:
          targets: artifact-all
      -
        name: Move artifacts
        run: |
          mv ./dist/**/* ./dist/
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: xgo
          path: ./dist/*
          if-no-files-found: error
      -
        name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          files: |
            dist/*.tar.gz
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
