name: go

on:
  push:
    tags:
      - 'go-*'

env:
  DOCKERHUB_SLUG: crazymax/xgo
  GHCR_SLUG: ghcr.io/crazy-max/xgo
  BASE_IMAGE: ghcr.io/crazy-max/xgo:base
  LATEST_116: 1.16.1
  LATEST_115: 1.15.9

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.15.0
          - 1.15.1
          - 1.15.2
          - 1.15.3
          - 1.15.4
          - 1.15.5
          - 1.15.6
          - 1.15.7
          - 1.15.8
          - 1.15.9
          - 1.16.0
          - 1.16.1
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Prepare
        run: |
          TAGS="${{ matrix.go_version }}"
          if [ "${{ env.LATEST_116 }}" = "${{ matrix.go_version }}" ]; then
            TAGS="${TAGS},1.16.x,latest"
          elif [ "${{ env.LATEST_115 }}" = "${{ matrix.go_version }}" ]; then
            TAGS="${TAGS},1.15.x"
          fi
          echo "TAGS=${TAGS}" >> $GITHUB_ENV
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            ${{ env.DOCKERHUB_SLUG }}
            ${{ env.GHCR_SLUG }}
          tag-custom: |
            ${{ env.TAGS }}
          tag-custom-only: true
          label-custom: |
            org.opencontainers.image.title=xgo (go-${{ matrix.go_version }})
            org.opencontainers.image.description=Go CGO cross compiler
            org.opencontainers.image.vendor=CrazyMax
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build
        uses: docker/bake-action@v1
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.docker_meta.outputs.bake-file }}
          targets: go-${{ matrix.go_version }}
