name: test

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build
        uses: docker/bake-action@v1
        with:
          targets: base
          set: |
            *.tags=test.internal/xgo:base
            *.output=type=docker,dest=/tmp/base.tar
      -
        name: Upload base image
        uses: actions/upload-artifact@v2
        with:
          name: base
          path: /tmp/base.tar

  test:
    runs-on: ubuntu-latest
    needs: [ base ]
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.15
          - 1.16
        case:
          - c
          - cpp
          - gorm
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Download base image
        uses: actions/download-artifact@v2
        with:
          name: base
          path: /tmp
      -
        name: Load Docker image
        run: |
          docker load --input /tmp/base.tar
          docker image inspect test.internal/xgo:base
      -
        name: Bootstrap ${{ matrix.go_version }}
        uses: docker/bake-action@v1
        with:
          targets: go-${{ matrix.go_version }}
          set: |
            *.tags=test.internal/xgo:${{ matrix.go_version }}
            *.output=type=docker
        env:
          BASE_IMAGE: xgo:base
      -
        name: Test ${{ matrix.case }} for go-${{ matrix.go_version }}
        uses: docker/bake-action@v1
        with:
          targets: test-${{ matrix.case }}
        env:
          BASE_IMAGE: test.internal/xgo:${{ matrix.go_version }}
