name: xgo

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Dump GitHub env
        run: |
          env
      -
        name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      -
        name: Set TAG_NAME
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "##[set-env name=TAG_NAME;]${GITHUB_REF#refs/tags/}"
      -
        name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.12.4
      -
        name: Set GOPATH
        # temporary fix (see https://github.com/actions/setup-go/issues/14)
        run: |
          echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
          echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
      -
        name: Checkout
        uses: actions/checkout@master
      -
        name: GoReleaser
        env:
          GORELEASER_VERSION: 0.118.0
        run: |
          curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh -s v${GORELEASER_VERSION}
          if [[ -z "$TAG_NAME" ]]; then
            echo GoReleaser Snapshot
            ./bin/goreleaser release --snapshot --rm-dist
          else
            echo GoReleaser Release
            ./bin/goreleaser release --skip-publish --rm-dist
            rm -f dist/CHANGELOG.md dist/config.yaml
          fi
          for folder in dist/*; do
            if [ -d ${folder} ]; then
              filename=$(basename $folder)
              if [[ $filename == *"windows"* ]]; then
                filename=${filename}.exe
              fi
              for xgo in ${folder}/*; do
                mv "${xgo}" "dist/${filename}.tmp"
                rm -rf "${folder}"
                mv "dist/${filename}.tmp" "dist/${filename}"
              done
            fi
          done
      -
        name: GitHub Release
        if: success() && startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go get -u github.com/tcnksm/ghr
          ghr --version
          ghr -n ${TAG_NAME} -draft ${TAG_NAME} dist/
